export const memberInfo = {
    "sex":[
        {"label":"请选择","value":0,"disabled":true},
        {"label":"先生","value":1},
        {"label":"女士","value":2}
    ],
    "degree":[
        {"label":"请选择","value":0,"disabled":true},
        {"label":"初中及以下","value":1},
        {"label":"高中/中专","value":2},
        {"label":"大专","value":3},
        {"label":"本科","value":4},
        {"label":"硕士及以上","value":5}
    ],
    "newEnergyCarCognitive":[
        {"label":"请选择","value":0,"disabled":true},
        {"label":"很了解","value":1},
        {"label":"关注中","value":2},
        {"label":"不了解","value":3},
        {"label":"没兴趣","value":4}
    ],
    "haveCarNum":[
        {"label":"请选择","value":0},
        {"label":"1辆","value":1},
        {"label":"2辆及以上","value":2},
        {"label":"没有","value":3}
    ],
    "haveCarBrand":[
        {
            "label":"请选择",
            "value":0,
            "children":[
                {
                    "label":"请选择",
                    "value":0
                }
            ]
        },
        {
            "label":"本田",
            "value":1
        },
        {
            "label":"丰田",
            "value":2
        },
        {
            "label":"三菱",
            "value":3
        },
        {
            "label":"斯巴鲁",
            "value":4
        },
        {
            "label":"铃木",
            "value":5
        },
        {
            "label":"日产",
            "value":6
        },
        {
            "label":"马自达",
            "value":7
        },
        {
            "label":"讴歌",
            "value":8
        },
        {
            "label":"雷克萨斯",
            "value":9,
            "children":[
                {
                    "label":"CT",
                    "value":0
                },
                {
                    "label":"IS",
                    "value":1
                },
                {
                    "label":"ES",
                    "value":2
                },
                {
                    "label":"GS",
                    "value":3
                },
                {
                    "label":"LS",
                    "value":4
                },
                {
                    "label":"NX",
                    "value":5
                },
                {
                    "label":"GX",
                    "value":6
                },
                {
                    "label":"RX",
                    "value":7
                },
                {
                    "label":"LX",
                    "value":8
                },
                {
                    "label":"LC",
                    "value":9
                },
                {
                    "label":"RC",
                    "value":10
                }
            ]
        },
        {
            "label":"英菲尼迪",
            "value":10,
            "children":[
                {
                    "label":"Q50",
                    "value":0
                },
                {
                    "label":"Q70",
                    "value":1
                },
                {
                    "label":"ESQ",
                    "value":2
                },
                {
                    "label":"QX30",
                    "value":3
                },
                {
                    "label":"QX60",
                    "value":4
                },
                {
                    "label":"QX70",
                    "value":5
                },
                {
                    "label":"QX80",
                    "value":6
                },
                {
                    "label":"Q60",
                    "value":7
                }
            ]
        },
        {
            "label":"奥迪",
            "value":11,
            "children":[
                {
                    "label":"A1",
                    "value":0
                },
                {
                    "label":"A3",
                    "value":1
                },
                {
                    "label":"A4",
                    "value":2
                },
                {
                    "label":"A5",
                    "value":3
                },
                {
                    "label":"A6",
                    "value":4
                },
                {
                    "label":"A7",
                    "value":5
                },
                {
                    "label":"A8",
                    "value":6
                },
                {
                    "label":"Q3",
                    "value":7
                },
                {
                    "label":"Q5",
                    "value":8
                },
                {
                    "label":"Q7",
                    "value":9
                },
                {
                    "label":"TT",
                    "value":10
                },
                {
                    "label":"R8",
                    "value":11
                }
            ]
        },
        {
            "label":"保时捷",
            "value":12,
            "children":[
                {
                    "label":"Panamera",
                    "value":0
                },
                {
                    "label":"Macan",
                    "value":1
                },
                {
                    "label":"Cayenne",
                    "value":2
                },
                {
                    "label":"718",
                    "value":3
                },
                {
                    "label":"911",
                    "value":4
                }
            ]
        },
        {
            "label":"宝马",
            "value":13,
            "children":[
                {
                    "label":"1系",
                    "value":0
                },
                {
                    "label":"2系",
                    "value":1
                },
                {
                    "label":"3系",
                    "value":2
                },
                {
                    "label":"4系",
                    "value":3
                },
                {
                    "label":"5系",
                    "value":4
                },
                {
                    "label":"6系",
                    "value":5
                },
                {
                    "label":"7系",
                    "value":6
                },
                {
                    "label":"X1",
                    "value":7
                },
                {
                    "label":"X3",
                    "value":8
                },
                {
                    "label":"X4",
                    "value":9
                },
                {
                    "label":"X5",
                    "value":10
                },
                {
                    "label":"X6",
                    "value":11
                },
                {
                    "label":"i8",
                    "value":12
                },
                {
                    "label":"Z4",
                    "value":13
                }
            ]
        },
        {
            "label":"奔驰",
            "value":14,
            "children":[
                {
                    "label":"A级",
                    "value":0
                },
                {
                    "label":"B级",
                    "value":1
                },
                {
                    "label":"C级",
                    "value":2
                },
                {
                    "label":"E级",
                    "value":3
                },
                {
                    "label":"R级",
                    "value":4
                },
                {
                    "label":"GLA",
                    "value":5
                },
                {
                    "label":"GLC",
                    "value":6
                },
                {
                    "label":"GLE",
                    "value":7
                },
                {
                    "label":"GLS",
                    "value":8
                },
                {
                    "label":"AMG",
                    "value":9
                }
            ]
        },
        {
            "label":"大众",
            "value":15
        },
        {
            "label":"迈巴赫",
            "value":16
        },
        {
            "label":"迈凯伦",
            "value":17
        },
        {
            "label":"欧宝",
            "value":18
        },
        {
            "label":"smart",
            "value":19
        },
        {
            "label":"威兹曼",
            "value":20
        },
        {
            "label":"斯柯达",
            "value":21
        },
        {
            "label":"别克",
            "value":22
        },
        {
            "label":"道奇",
            "value":23
        },
        {
            "label":"福特",
            "value":24,
            "children":[
                {
                    "label":"福克斯",
                    "value":0
                },
                {
                    "label":"福睿斯",
                    "value":1
                },
                {
                    "label":"金牛座",
                    "value":2
                },
                {
                    "label":"蒙迪欧",
                    "value":3
                },
                {
                    "label":"翼搏",
                    "value":4
                },
                {
                    "label":"翼虎",
                    "value":5
                },
                {
                    "label":"锐界",
                    "value":6
                },
                {
                    "label":"嘉年华",
                    "value":7
                },
                {
                    "label":"致胜",
                    "value":8
                },
                {
                    "label":"麦柯斯",
                    "value":9
                }
            ]
        },
        {
            "label":"悍马",
            "value":25
        },
        {
            "label":"JEEP吉普",
            "value":26
        },
        {
            "label":"凯迪拉克",
            "value":27,
            "children":[
                {
                    "label":"ATS",
                    "value":0
                },
                {
                    "label":"CT6",
                    "value":1
                },
                {
                    "label":"XTS",
                    "value":2
                },
                {
                    "label":"XT5",
                    "value":3
                }
            ]
        },
        {
            "label":"林肯",
            "value":28,
            "children":[
                {
                    "label":"MKZ",
                    "value":0
                },
                {
                    "label":"林肯大陆",
                    "value":1
                },
                {
                    "label":"MKC",
                    "value":2
                },
                {
                    "label":"MKX",
                    "value":3
                },
                {
                    "label":"领航员",
                    "value":4
                }
            ]
        },
        {
            "label":"特斯拉",
            "value":29,
            "children":[
                {
                    "label":"Model S",
                    "value":0
                },
                {
                    "label":"Model X",
                    "value":1
                }
            ]
        },
        {
            "label":"雪佛兰",
            "value":30
        },
        {
            "label":"起亚",
            "value":31
        },
        {
            "label":"双龙",
            "value":32
        },
        {
            "label":"现代",
            "value":33
        },
        {
            "label":"标致",
            "value":34
        },
        {
            "label":"雪铁龙",
            "value":35
        },
        {
            "label":"布加迪",
            "value":36
        },
        {
            "label":"DS",
            "value":37
        },
        {
            "label":"雷诺",
            "value":38
        },
        {
            "label":"阿斯顿·马丁",
            "value":39
        },
        {
            "label":"宾利",
            "value":40
        },
        {
            "label":"劳斯莱斯",
            "value":41
        },
        {
            "label":"路特斯",
            "value":42
        },
        {
            "label":"MG名爵",
            "value":43
        },
        {
            "label":"摩根",
            "value":44
        },
        {
            "label":"世爵",
            "value":45
        },
        {
            "label":"路虎",
            "value":46,
            "children":[
                {
                    "label":"发现神行",
                    "value":0
                },
                {
                    "label":"极光",
                    "value":1
                },
                {
                    "label":"发现",
                    "value":2
                },
                {
                    "label":"星脉",
                    "value":3
                },
                {
                    "label":"揽胜",
                    "value":4
                },
                {
                    "label":"揽运",
                    "value":5
                }
            ]
        },
        {
            "label":"捷豹",
            "value":47
        },
        {
            "label":"阿尔法·罗密欧",
            "value":48
        },
        {
            "label":"菲亚特",
            "value":49
        },
        {
            "label":"法拉利",
            "value":50
        },
        {
            "label":"兰博基尼",
            "value":51
        },
        {
            "label":"玛莎拉蒂",
            "value":52
        },
        {
            "label":"帕加尼",
            "value":53
        },
        {
            "label":"比亚迪",
            "value":54
        },
        {
            "label":"其他",
            "value":55
        }
    ],
    "interest":[
        {"name":"沙龙","value":1,"checked":false},
        {"name":"试驾","value":2,"checked":false},
        {"name":"新品上市","value":3,"checked":false},
        {"name":"自驾旅行","value":4,"checked":false},
        {"name":"摄影","value":5,"checked":false},
        {"name":"艺术展览","value":6,"checked":false}
    ]
}